In [1]:
import numpy as np

## NumPy Broadcasting (Scalar with Array)

In [2]:
arr = np.array([1, 2, 3, 4, 5])
scalar = 10

# Broadcasting scalar to array
arr + scalar

array([11, 12, 13, 14, 15])

##  Broadcasting with 2D Array and 1D Array

In [3]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

vector = np.array([10, 20, 30])

# Broadcasting vector across rows
matrix + vector

array([[11, 22, 33],
       [14, 25, 36]])

## Broadcasting Rules Example

In [4]:
a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])

a + b

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

##  Vectorization vs Loop

In [5]:
arr = np.array([1, 2, 3, 4, 5])

# Using loop
loop_result = []
for i in arr:
    loop_result.append(i * 2)

loop_result

[np.int64(2), np.int64(4), np.int64(6), np.int64(8), np.int64(10)]

In [6]:
# Using vectorization
arr * 2

array([ 2,  4,  6,  8, 10])

##  Performance Comparison

In [7]:
import time

large_array = np.arange(1_000_000)

# Loop approach
start = time.time()
loop_result = []
for i in large_array:
    loop_result.append(i * 2)
print("Loop Time:", time.time() - start)

# Vectorized approach
start = time.time()
vectorized_result = large_array * 2
print("Vectorized Time:", time.time() - start)

Loop Time: 0.45304036140441895
Vectorized Time: 0.004397869110107422
