In [1]:
import numpy as np

In [2]:
# Creating array using np
arr = np.array([1,2,3,4,5])
print(arr,type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [3]:
# Create Array -from lists
arr = np.array([1,2,3,4,5])
print(arr,type(arr),arr.dtype,arr.shape)

arr2= np.array([1,2,3,4,5,"pankaj"])
print(arr2,type(arr2),arr2.dtype,arr2.shape)

arr2d =np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr2d,arr2d.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'pankaj'] <class 'numpy.ndarray'> <U21 (6,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


In [4]:
# Create
print("creating array ")
# using zeros
print("using zeros")
arr1 = np.zeros((2,3),dtype ="int64")
print(arr1,arr1.shape)

# using ones
print("using ones")
arr2 = np.ones((2,3),dtype="int64")
print(arr2,arr2.shape)

# for 1D array
print("using ones")
arr3 = np.ones((5,)) #prefill
print(arr3,arr3.shape)

# prefill with values
print("prefill with values")
arr4 = np.full((3,4),100)  #prefill with values
print(arr4,arr4.shape)

# identity matrix
print("identity matrix")
arr5 = np.eye((3), dtype="int64") #identity matrix
print(arr5,arr5.shape)

# arange() ----> same as range() in python
print("arange function in np")
arr6 = np.arange(1,10)   #range elements
print(arr6,arr6.shape)

# linspace() ----> evenly create spaced array
print("linespace in np")
arr7 = np.linspace(1,100,4)  #evenly spaced array
print(arr7,arr7.shape)

creating array 
using zeros
[[0 0 0]
 [0 0 0]] (2, 3)
using ones
[[1 1 1]
 [1 1 1]] (2, 3)
using ones
[1. 1. 1. 1. 1.] (5,)
prefill with values
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
identity matrix
[[1 0 0]
 [0 1 0]
 [0 0 1]] (3, 3)
arange function in np
[1 2 3 4 5 6 7 8 9] (9,)
linespace in np
[  1.  34.  67. 100.] (4,)
